version: "3.9"
services:
  dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    env_file: ../.env
    volumes:
      - "..:/app"
    ports:
      - "8000:8000"
      - "8888:8888"  # Jupyter
    command: /bin/bash
    stdin_open: true
    tty: true 